name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  RESOURCE-GROUP: rg-eshoponweb-brami
  LOCATION: eastus
  SUBSCRIPTION-ID: 2850e1d9-c302-4a1d-a682-1a7a802d6540
  WEBAPP-NAME: eshoponweb-uniquealias

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload artifact for bicep template
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: bicep-template/webapp.bicep  # Update this path if necessary

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    steps:
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./net-app

      - name: Download bicep template
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: ./bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: ./bicep-template/webapp.bicep  # Ensure this path is correct
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false
